### ISSUE TITLE
Question on how to weight the box loss with quality score?

### ISSUE THREAD

**Issue by huangh12** [implus/GFocalV2#25]
Hi @implus ,  thanks for the impressive GFocal/GFocalV2 work. From the paper, the box related loss is weigted by the quality score.
![图片](https://user-images.githubusercontent.com/18748036/124374077-ca45ab00-dcca-11eb-944a-9b78022f4c79.png)
However,  I've read the released GFocal and GFocalV2 code, and find the weighting detail differs from the mmdetetion/FCOS offical code.
Specifically, in GFocal/GFocalV2, the weight is the **predicted** quality score i.e., cls_score. 

https://github.com/implus/GFocalV2/blob/b7b355631daaf776e097a6e137501aa27ff7e757/mmdet/models/dense_heads/gfocal_head.py#L287

while in the mmdetetion, the weight is the **targeted** quality score, i.e., centerness_targets.
https://github.com/open-mmlab/mmdetection/blob/321eb30034602085821b710108fb4ce4323f69f9/mmdet/models/dense_heads/atss_head.py#L201

Is your weighting mechinam an intented design or just a typo?  Did you find any accuracy gain from yours? From my point of view, using quality target to weight the box loss seems more rational. Because at the begining of training, the predicted quality score could be very noisy, which may hamper the box regression.

**Comment by implus** [comment]
In our prior experiments, using predicted quality has no difference with using targeted one in final performance. But I prefer using the predicted one because it is more aligned with prediction formula during inference, i.e., if our detector can not make accurate prediction on quality scores of certain valid targets, it makes no sence to assign it with higher learning weight.
